name: box_this
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  flutter_svg: ^2.2.0
  intl: ^0.20.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  
flutter_native_splash:
  # Erforderlicher Parameter: Legt die Hintergrundfarbe fest. Verwenden Sie einen Hex-Code.
  color: "#FAFAFA" 
  # Pfad zu Ihrem Splash-Bild. Dies wird in der Mitte des Bildschirms angezeigt.
  image: assets/splash/splash.png



flutter:
  uses-material-design: true

  assets:
    - assets/svg/icons/
    - assets/fonts/
    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/AppIcon.png"

  
